@MusicManagementDemo_HostAddress = http://localhost:5095

GET {{MusicManagementDemo_HostAddress}}/health/live/
Accept: text/plain

###

GET {{MusicManagementDemo_HostAddress}}/health/ready/
Accept: text/plain

###